# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  MasterNodes = 1

  (1..MasterNodes).each do |i|

    config.vm.define "k0s-master0#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      node.vm.box_check_update  = false
      node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "k0s-master0#{i}"
      node.vm.network "private_network", ip: "172.42.42.10#{i}"


      node.vm.provider :virtualbox do |v|
        v.name    = "k0s-master0#{i}"
        v.memory  = 2048
        v.cpus    = 2
      end

    end

  end

  WorkerNodes = 1

  (1..WorkerNodes).each do |i|

    config.vm.define "k0s-worker0#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      node.vm.box_check_update  = false
      node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "k0s-worker0#{i}"
      node.vm.network "private_network", ip: "172.42.42.20#{i}"


      node.vm.provider :virtualbox do |v|
        v.name    = "k0s-worker0#{i}"
        v.memory  = 2048
        v.cpus    = 2
      end

    end

  end

end
